
# clusterregistry/resource-enforced-selector.yaml

apiVersion: configmanagement.gke.io/v1
kind: ClusterSelector
metadata:
  name: resource-enforced-clusters
spec:
  selector:
    matchLabels:
      # This policy applies ONLY to clusters with this label in the fleet
      policy-group: custom-template-enabled
      # You could also add 'tier: high-perf' or similarapiVersion: constraints.gatekeeper.sh/v1beta1
---
